#!/bin/bash


Arguments=Condor/Inputs/ArgumentsForCondorMerge2DHistos.txt
rm $Arguments





#echo "EmptyTimePiX">>${Arguments}
echo "Y_Mo">>${Arguments}
echo "Cs_Mo">>${Arguments}
echo "AmBe_Mo">>${Arguments}
echo "Empty_Mo">>${Arguments}
echo "Pb_Mo">>${Arguments}
echo "C_Mo">>${Arguments}
echo "Background_Mo">>${Arguments}
echo "Au_Mo">>${Arguments}


more $Arguments
condor_submit Condor/ProgramsLaunch/LaunchCondorMergeMake2D.sh






exit

