#!/bin/bash


Arguments=Condor/Inputs/ArgumentsForCondorMerge2DHistos.txt
rm $Arguments





#echo "EmptyTimePiX">>${Arguments}
echo "Y">>${Arguments}
echo "Cs">>${Arguments}
echo "Background">>${Arguments}
echo "Empty_Er">>${Arguments}
echo "C_2_6000">>${Arguments}
echo "Au_13_100">>${Arguments}
echo "Au_40_200">>${Arguments}
echo "Er167_13">>${Arguments}





more $Arguments
condor_submit Condor/ProgramsLaunch/LaunchCondorMergeMake2D.sh






exit

